### ISSUE TITLE
Error with apostrophes

### ISSUE THREAD

**Issue by Spigushe** [Spigushe/krcg#3]
Getting a compilation error on this file and some others, using this one to figure out why
```python
[2020-06-11 23:28:16,534] ERROR in app: Exception on /en/archetypes/baltimore-purge.html [GET]
Traceback (most recent call last):
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/spigushe/Documents/Codex-of-the-Damned/krcg/codex/__init__.py", line 69, in index
    return flask.render_template(page, language=flask.g.get("lang_code"))
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/Users/spigushe/krcg/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/Users/spigushe/Documents/Codex-of-the-Damned/krcg/codex/templates/archetypes/baltimore-purge.html", line 38, in template
    {{ card("Zillah's Valley") }},
jinja2.exceptions.TemplateSyntaxError: expected token ',', got 's'
```

**Comment by Spigushe** [comment]
path: `codex/templates/archetypes/baltimore-purge.html`

**Comment by lionel-panhaleux** [comment]
You're missing a closing single quote somewhere before:
https://github.com/Spigushe/krcg/blob/master/codex/templates/archetypes/baltimore-purge.html#L5

**Comment by Spigushe** [comment]
thx
